Update to use plugin type mechanism to load components. Started adding network mesh

diff --git a/lib/cni/container-networking-setup b/lib/cni/container-networking-setup
--- a/lib/cni/container-networking-setup
+++ b/lib/cni/container-networking-setup
@@ -1,39 +1,32 @@
 #!/bin/bash 
 #
-# Script to setup container networking
+# Script to install container networking
 #
 # Depends on:
-#  1. container-networking-calico
-# 
+# 1. bash-lib-logging
+# 2. bash-lib-execmd
+#
 
-containerNetworking_setup()
+containerNetworking_install()
 {
 	local _CONTAINER_NETWORKING_TYPE=$1
-	case ${_CONTAINER_NETWORKING_TYPE} in
-		calico)
-			calico_setup
-			;;
-		flannel)
-			flannel_setup
-			;;
-		cilium)
-			cilium_setup
-			;;
-		*)
-			log   "Unable to setup container networking [${_CONTAINER_NETWORKING_TYPE}]"
-			abort "Not yet implemented"
-			;;
-	esac
+	local func="${_CONTAINER_NETWORKING_TYPE}_install"
+	if (( $(isFunction ${func}) )); then
+		${func}
+		if (( $? )); then
+			abort "Failed to install [${_CONTAINER_NETWORKING_TYPE}] container networking" 
+		else
+			log "Successfully installed [${_CONTAINER_NETWORKING_TYPE}] container networking" 
+		fi
+	else
+		log   "Unable to install container networking [${_CONTAINER_NETWORKING_TYPE}]"
+		abort "Not yet implemented"
+	fi 
 }
 
 containerNetworking_prepare_for_reinstall()
 {
-	local _CONTAINER_NETWORKING_TYPE=$1
-	case ${_CONTAINER_NETWORKING_TYPE} in
-		*)
-			:  # Nothing to do 
-			;;
-	esac 
+	:  # Nothing to do 
 }
 
 #::END::
diff --git a/lib/cri/container-runtime-setup b/lib/cri/container-runtime-setup
--- a/lib/cri/container-runtime-setup
+++ b/lib/cri/container-runtime-setup
@@ -3,35 +3,42 @@
 # Script to install container runtime
 #
 # Depends on:
-#  1. container_runtime_docker
+#  1. bash-lib-logging
+#  2. bash-lib-execmd
 # 
 
 containerRuntime_install()
 {
 	local _CONTAINER_RUNTIME=$1
-	case ${_CONTAINER_RUNTIME} in
-		docker)
-			docker_install
-			;;
-		*)
-			log   "Unable to install container runtime [${_CONTAINER_RUNTIME}]"
-			abort "Not yet implemented"
-			;;
-	esac
+	local func="${_CONTAINER_RUNTIME}_install"
+	if (( $(isFunction ${func}) )); then
+		${func}
+		if (( $? )); then
+			abort "Unable to install container runtime [${_CONTAINER_RUNTIME}]" 
+		else
+			log "Successfully installed container runtime [${_CONTAINER_RUNTIME}]" 
+		fi
+	else
+		log   "Unable to install container runtime [${_CONTAINER_RUNTIME}]"
+		abort "Not yet implemented"
+	fi
 }
 
 containerRuntime_prepare_for_reinstall()
 {
 	local _CONTAINER_RUNTIME=$1
-	case ${_CONTAINER_RUNTIME} in
-		docker)
-			docker_prepare_for_reinstall
-			;;
-		*)
-			log   "Unable to prepare container runtime [${_CONTAINER_RUNTIME}] for reinstall."
-			abort " Not yet implemented"
-			;;
-	esac 
+	local func="${_CONTAINER_RUNTIME}_prepare_for_reinstall"
+	if (( $(isFunction ${func}) )); then
+		${func}
+		if (( $? )); then
+			abort "Failed to prepare container runtime [${_CONTAINER_RUNTIME}] for reinstallation." 
+		else
+			log "Successfully prepared container runtime [${_CONTAINER_RUNTIME}] for reinstallation." 
+		fi
+	else
+		log   "Unable to prepare container runtime [${_CONTAINER_RUNTIME}] for reinstall."
+		abort "Not yet implemented"
+	fi
 }
 
 #::END::
